// Fixed first probe. Exported mockable engine; executable entry remains hard-disabled.
import {readFileSync,openSync,writeSync,fsyncSync,closeSync,existsSync,mkdirSync} from 'node:fs';
import {CONTRACT,canonical,sha,baseContext,ACCOUNT,DB} from './atomicity-schema-audit.mjs';
export const PLAN_SHA='cc4e854c77a5e3115999c7271abeb83974911b353b9afeeab3d8ae08d7d7fb28';
export const PLAN=JSON.parse(readFileSync(new URL('./atomicity-test-plan.json',import.meta.url)));
export const READ_ROW='SELECT * FROM backend_probe_v1 WHERE platform=? AND account_id=? AND intent_id=?';
export function validatePlan(raw=readFileSync(new URL('./atomicity-test-plan.json',import.meta.url))){if(sha(raw)!==PLAN_SHA||PLAN.schema_fingerprint!==CONTRACT.schema_fingerprint||PLAN.steps.length!==9)throw Error('PLAN_DRIFT');const receipt=readFileSync(new URL('../audit-evidence/d1-v2-migration-receipt-37098401244.json',import.meta.url));if(sha(receipt)!==PLAN.migration_receipt_sha256)throw Error('MIGRATION_RECEIPT_DRIFT');return true;}
export const ATOMICITY_ACTIVATION_MESSAGE='PLM execute owner-approved fixed atomicity once 20261003-r1';
export function executionGate(e){const pinned=e.GITHUB_SHA===e.PLM_ATOMICITY_APPROVED_COMMIT||(e.PLM_ATOMICITY_EXECUTION_CODE_COMMIT===e.PLM_ATOMICITY_APPROVED_COMMIT&&e.PLM_ATOMICITY_EVENT_BEFORE===e.PLM_ATOMICITY_APPROVED_COMMIT&&e.PLM_ATOMICITY_ACTIVATION_MESSAGE===ATOMICITY_ACTIVATION_MESSAGE);return baseContext(e)&&e.GITHUB_EVENT_NAME==='push'&&e.PLM_ATOMICITY_ALLOW==='true'&&e.PLM_ATOMICITY_OWNER_APPROVAL==='EXECUTE_FIXED_ATOMICITY_ONCE'&&/^[a-f0-9]{40}$/.test(e.GITHUB_SHA||'')&&/^[a-f0-9]{40}$/.test(e.PLM_ATOMICITY_APPROVED_COMMIT||'')&&pinned&&e.PLM_ATOMICITY_PLAN_SHA===PLAN_SHA&&!!e.PLM_CF_D1_ATOMICITY_TEST_TOKEN&&!!e.PLM_CF_D1_READ_TOKEN&&!e.PLM_CF_D1_MIGRATION_V2_TOKEN&&!e.PLM_CF_D1_API_TOKEN&&!e.PLM_CF_WORKER_API_TOKEN;}

export function materialize(step,t0,winner){const vars={T0:t0,T1:t0+1,T2:t0+2,WINNER:winner,LOSER:winner==='contender_a'?'contender_b':'contender_a'};return {sql:step.sql,params:step.params.map(x=>Object.hasOwn(vars,x)?vars[x]:x)};}
export function expectedRow(version,t0,winner){const f=PLAN.expected_final_row;return {...f,owner:version===1?null:winner,owner_epoch:version===1?0:1,fencing_token:version===1?0:1,state:version===1?'ready':version===2?'claimed':'succeeded',version,last_request_id:version===1?'init':version===2?(winner==='contender_a'?'claim_a':'claim_b'):'terminal',delivery_id:version===3?'delivery_001':null,result_id:version===3?'result_001':null,created_at:t0,updated_at:t0+version-1};}
export function exclusiveJournal(dir){if(existsSync(dir))throw Error('PREVIOUS_SENT_OR_UNKNOWN_NO_RESUME');mkdirSync(dir,{recursive:false,mode:0o700});const saved=new Set();return {reserve(id,data){if(saved.has(id))throw Error('DUPLICATE_SEND');const fd=openSync(`${dir}/${id}.SENT.json`,'wx',0o600);try{writeSync(fd,JSON.stringify({id,status:'SENT',...data})+'\n');fsyncSync(fd);}finally{closeSync(fd);}saved.add(id);},finish(id,status){const fd=openSync(`${dir}/${id}.${status}.json`,'wx',0o600);try{writeSync(fd,JSON.stringify({id,status})+'\n');fsyncSync(fd);}finally{closeSync(fd);}}};}
export async function historyClear(fetchPage,currentRun){const seen=new Set();let total;for(let page=1;page<=100;page++){const d=await fetchPage(page);if(!Array.isArray(d.workflow_runs)||!Number.isSafeInteger(d.total_count))return false;if(total===undefined)total=d.total_count;if(total!==d.total_count)return false;for(const r of d.workflow_runs){if(seen.has(r.id))return false;seen.add(r.id);if(String(r.id)!==String(currentRun)&&r.conclusion!=='skipped')return false;}if(seen.size===total)return true;if(d.workflow_runs.length===0||seen.size>total)return false;}return false;}
export function reconcile(row,expected,primary,ackZero=false){if(!primary)return 'STILL_UNKNOWN';if(canonical(row)===canonical(expected))return 'COMMITTED';if(ackZero)return 'NOT_COMMITTED';return 'STILL_UNKNOWN';}
export async function runProbe(e,io,{journal,historyVerified=false,schemaVerified=false,t0=Math.floor(Date.now()/1000)}={}){
 const r={status:'BLOCKED',mutation_submissions:0,successful_logical_row_changes:0,reconciliation_sets:0,retry:0,resend:0,delete:0,deploy:0,worker_invocation:0,live_jobs:0,render:0,posting:0,live_ready:false,posting_permitted:false,steps:[],primary_readbacks:[],unknown_count:0,fallback:0,row_reset:0,automatic_rollback:0};
 if(!executionGate(e)||!historyVerified||!schemaVerified||!journal||!Number.isSafeInteger(t0)||t0<=0)return r;validatePlan();let winner=null,version=0,unknownSteps=[];
 async function readExpect(v){const q=await io.read();if(q.primary!==true||canonical(q.row)!==canonical(v===0?null:expectedRow(v,t0,winner)))throw Error('ROW_CHECK_FAILED');r.primary_readbacks.push({after_submission:r.mutation_submissions,served_by_primary:true,row:q.row});}
 async function send(step){r.mutation_submissions++;const started=Date.now();let q;try{q=await io.mutate(materialize(step,t0,winner));if(!Number.isSafeInteger(q.changes)||q.changes<0||q.changes>1)throw Error('AFFECTED_ROWS_UNKNOWN');}catch{r.unknown_count++;unknownSteps.push(step);journal.finish(step.id,'UNKNOWN');throw Error('MUTATION_UNKNOWN_NO_RESEND');}r.successful_logical_row_changes+=q.changes;journal.finish(step.id,'ACK');r.steps.push({id:step.id,changes:q.changes,start_ms:started,end_ms:Date.now(),http_status:q.http_status??200});if(step.expected_changes!==null&&q.changes!==step.expected_changes)throw Error('UNEXPECTED_AFFECTED_ROWS_STOP');if(r.successful_logical_row_changes>3)throw Error('UNEXPECTED_AFFECTED_ROWS_STOP');return q.changes;}

 try{
  await readExpect(0);
  for(let i=0;i<9;i++){
   if(i===2){const group=PLAN.steps.slice(2,4);for(const s of group)journal.reserve(s.id,{plan_sha:PLAN_SHA,t0});const results=await Promise.allSettled(group.map(send));if(results.some(x=>x.status!=='fulfilled'))throw Error('MUTATION_UNKNOWN_NO_RESEND');const changes=results.map(x=>x.value);if(changes[0]+changes[1]!==1)throw Error('CONCURRENT_CAS_INVARIANT');winner=changes[0]===1?'contender_a':'contender_b';const times=r.steps.slice(-2);r.client_overlap_ms=Math.min(...times.map(x=>x.end_ms))-Math.max(...times.map(x=>x.start_ms));if(r.client_overlap_ms<=0)throw Error('CLIENT_REQUESTS_NOT_OVERLAPPING');r.client_request_overlap=true;r.claim_winner=winner;r.claim_loser=winner==='contender_a'?'contender_b':'contender_a';r.d1_internal_parallel_execution_claimed=false;version=2;await readExpect(version);i=3;continue;}
   const step=PLAN.steps[i];journal.reserve(step.id,{plan_sha:PLAN_SHA,t0});const n=await send(step);if(n!==step.expected_changes)throw Error('UNEXPECTED_AFFECTED_ROWS_STOP');version=step.expected_next_version;await readExpect(version);
  }
  r.final_row=r.primary_readbacks.at(-1).row;r.logical_timestamp_T0=t0;r.status='PASS_BOUNDED_FIRST_PROBE';
 }catch(err){r.status='STOP';r.failure_code=['ROW_CHECK_FAILED','CONCURRENT_CAS_INVARIANT','CLIENT_REQUESTS_NOT_OVERLAPPING','UNEXPECTED_AFFECTED_ROWS_STOP'].includes(err.message)?err.message:'MUTATION_UNKNOWN_NO_RESEND';if(['MUTATION_UNKNOWN_NO_RESEND','ROW_CHECK_FAILED'].includes(r.failure_code)&&r.mutation_submissions){r.reconciliation_sets=1;try{const q=await io.read();const options=r.failure_code==='ROW_CHECK_FAILED'?[expectedRow(version,t0,winner)]:unknownSteps.filter(s=>s.expected_changes===1||s.group==='concurrent_claim').map(s=>expectedRow(s.expected_next_version,t0,s.id==='03_claim_a'?'contender_a':s.id==='04_claim_b'?'contender_b':winner));r.reconciliation=options.some(x=>canonical(x)===canonical(q.row))&&q.primary===true?'COMMITTED':'STILL_UNKNOWN';}catch{r.reconciliation='STILL_UNKNOWN';}}r.manual_reconciliation_required=true;}
 return r;
}
